#!/usr/bin/env bash
set -euo pipefail

# global variables
# set in _set_global_var()

# ----- PRINT FUNCTIONS -----

# Set text colours if supported.
# Arguments:
#   $1: boolean indicating if colours is enabled
colours() {
  NC="" BOLD="" RED="" GREEN="" YELLOW="" BLUE="" MAGENTA="" CYAN=""
  if [[ $(tput colors) -ge 8 ]] && [[ $1 = true ]]; then
    NC=$(tput sgr0) BOLD=$(tput bold) # text reset (select graphic representation default)
    RED=$(tput setaf 1) GREEN=$(tput setaf 2) YELLOW=$(tput setaf 3) BLUE=$(tput setaf 4) MAGENTA=$(tput setaf 5) CYAN=$(tput setaf 6)
  fi
  brwne_txt="${RED}b${YELLOW}r${GREEN}w${CYAN}n${BLUE}e${NC}"
}

_info_msg() { printf "%s\n" "${BOLD}${BLUE}Info:${NC} $1"; }

_success_msg() { printf "%s\n" "${BOLD}${GREEN}Success:${NC} $1"; }

_warning_msg() { printf "%s\n" "${BOLD}${YELLOW}Warning:${NC} $1"; }

_error_msg() { printf "%s\n" "${BOLD}${RED}Error:${NC} $1" && exit 1; }

_usage() {
  cat <<EOF
${brwne_txt} is an installer script for brwne.

${YELLOW}Usage:${NC} ${brwne_txt} ${CYAN}[Options]${NC} ${CYAN}[Command]${NC}

${YELLOW}Options:${NC}
  ${GREEN}-n, --no-colour      ${NC} Do not output any colour. Useful when redirecting output to a logfile
  ${GREEN}-h, --help           ${NC} Print help information

${YELLOW}Commands:${NC}
  ${GREEN}i, install  ${NC} Installs brwne app & VS Code extension

${YELLOW}Example:${NC} ${brwne_txt} ${CYAN}install${NC}

${YELLOW}Project Homepage:${NC} ${MAGENTA}https://github.com/The-Pirateship/brwne-releases${NC}
EOF
}

# ----- OPTIONS -----

# ----- SET GLOBAL VARIABLES -----

# ----- HELPERS -----

# ----- COMMANDS -----

install() {
  if [[ "$(uname -s)" == Linux ]]; then
    # # Linux install dependencies
    # sudo apt-get install -qq curl libwebkit2gtk-4.1-dev build-essential \
    #   libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev \
    #   libsoup-3.0-0

    if [[ $(uname -m) == x86_64 ]]; then
      local is_installed=0
      command -v brwne &>/dev/null || is_installed=1
      if command -v brwne &>/dev/null; then
        local local_version
        local remote_version
        local_version="v$(apt-cache policy brwne | grep Installed | awk '{print $2}')"
        remote_version="$(curl -sSL "https://api.github.com/repos/The-Pirateship/brwne-releases/releases/latest" \
          | grep tag_name | grep -o '"v.*"' | tr -d '"')"
        [[ $local_version == "$remote_version" ]] || is_installed=1
      fi
      if [[ $is_installed -eq 1 ]]; then
        _info_msg "Downloading and installing brwne app"
        curl -sSL -o /tmp/brwne_amd64.deb \
          https://github.com/The-Pirateship/brwne-releases/releases/latest/download/brwne_amd64.deb
        sudo dpkg -i /tmp/brwne_amd64.deb
        _success_msg "Successfully installed brwne app"
      else
        _info_msg "brwne app is already the latest version"
      fi
    fi
  elif [[ $(uname -s) == Darwin ]]; then
    if ! ls /Applications/brwne.app &>/dev/null; then
      _info_msg "Downloading and installing brwne app"
      curl -sSL -o /tmp/brwne_aarch64.dmg \
        https://github.com/The-Pirateship/brwne-releases/releases/latest/download/brwne_aarch64.dmg
      hdiutil attach /tmp/brwne_aarch64.dmg -nobrowse -quiet
      sudo cp -r /Volumes/brwne/brwne.app /Applications/
      hdiutil detach /Volumes/brwne -quiet
      _success_msg "Successfully installed brwne app"
    else
      _info_msg "brwne app already installed"
    fi
  fi

  # add VS Code to PATH for macOS
  if [[ $(uname -s) == Darwin ]] && ! command -v code &>/dev/null; then
    if ls "/Applications/Visual Studio Code.app/Contents/Resources/app/bin" &>/dev/null; then
      export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
      _info_msg "Added VS Code to PATH"
    else
      _warning_msg "VS Code installed, skipping extension installation"
    fi
  fi
  if command -v code &>/dev/null; then
    if ! code --list-extensions | grep -q 'pirateship\.brwne'; then
      code --install-extension pirateship.brwne
      _success_msg "Successfully installed brwne VS Cde extension"
    else
      _info_msg "brwne VS Code extension already installed"
    fi
  fi
}

# ----- MAIN -----

main() {
  colours true # PRINT FUNCTIONS

  [[ $# -gt 0 ]] || install

  while [[ $# -gt 0 ]]; do
    case $1 in
      -h | --help) _usage && exit ;;
      # OPTIONS
      -n | --no-colour) colours false ;;
      # COMMANDS
      i | install) install ;;
      *) _usage && _error_msg "Invalid argument(s)" ;;
    esac
    shift
  done
}

main "$@"
